# Generated by Django 5.1.1 on 2024-09-24 15:30

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=30, verbose_name='Nome do Evento')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], db_index=True, default='ativo', max_length=10, verbose_name='Status')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local')),
                ('data', models.DateTimeField(verbose_name='Data do evento')),
                ('duracao', models.TimeField(help_text='Ex: 2 horas e 30 minutos', verbose_name='Duração')),
                ('logo', stdimage.models.StdImageField(blank=True, default=None, force_min_size=False, null=True, upload_to='evento_logos/', variations={'thumb': {'crop': True, 'height': 250, 'width': 250}})),
            ],
        ),
    ]
