# Generated by Django 5.1.1 on 2024-09-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_string', models.CharField(max_length=6, verbose_name='Chave do Armário')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponivel')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(blank=True, null=True, verbose_name='Data do Emprestimo')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('armario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armarios.armario')),
            ],
        ),
    ]
