# Generated by Django 5.1.1 on 2024-09-24 15:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import stdimage.models
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('multado', models.BooleanField(default=False, verbose_name='Multado')),
                ('nome_completo', models.CharField(max_length=40, verbose_name='Nome Completo')),
                ('is_ativo', models.BooleanField(default=False, editable=False, verbose_name='Ativo?')),
                ('is_funcionario', models.BooleanField(default=False, editable=False, verbose_name='Funcionario?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AlunoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('BCC', 'Ciencia da Computação'), ('AG', 'Agronomia'), ('QI', 'Quimica Industrial'), ('ZO', 'Zootecnia')], max_length=3, verbose_name='Curso')),
                ('img', stdimage.models.StdImageField(default='default/default_user.avif', force_min_size=False, upload_to=usuarios.models.get_file_path, variations={'thumb': {'crop': True, 'height': 360, 'width': 360}}, verbose_name='Imagem')),
                ('turno', models.CharField(choices=[('Horário Integral', 'Horario Integral'), ('Noturno', 'Noturno')], default='#', max_length=18, verbose_name='Turno')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='ProfessorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(choices=[('CS', 'Ciência da Computação'), ('SE', 'Engenharia de Software'), ('AI', 'Inteligência Artificial'), ('DS', 'Data Science'), ('AG', 'Agronomia'), ('AP', 'Agropecuária'), ('AS', 'Agroecologia'), ('AGRO', 'Engenharia Agronômica'), ('ZO', 'Zootecnia'), ('VM', 'Medicina Veterinária'), ('ZOA', 'Produção Animal'), ('ZOA', 'Nutrição Animal'), ('QI', 'Química Industrial'), ('EQ', 'Engenharia Química'), ('CQ', 'Química'), ('MT', 'Materiais e Metalurgia')], max_length=4, verbose_name='Formação')),
                ('img', stdimage.models.StdImageField(default='default/default_user.avif', force_min_size=False, upload_to=usuarios.models.get_file_path, variations={'thumb': {'crop': True, 'height': 360, 'width': 360}}, verbose_name='Imagem')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
    ]
