# Generated by Django 5.1.1 on 2025-06-08 21:36

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=stdimage.models.StdImageField(blank=True, default='profiles/pp_default.avif', force_min_size=False, null=True, upload_to='profiles', variations={'thumb': {'crop': True, 'height': 360, 'width': 360}}, verbose_name='Imagem'),
        ),
    ]
